# Schema for the configuration files of the VBase profile.

vbase.settings.tags:
  type: config_object
  label: 'VBase tags settings'
  mapping:
    generator:
      type: boolean
      label: 'Show generator metatag'
    mobile:
      type: boolean
      label: 'Show mobile optimized metatags'
    viewport:
      type: boolean
      label: 'Show viewport metatag'
    telephone:
      type: boolean
      label: 'Telephone detection'
    ie_chrome:
      type: boolean
      label: 'Show X-UA-Compatible'
    google_verification:
      label: 'Google Webmasters Verification'
      type: sequence
      sequence:
        type: string
        label: 'Code'
    yandex_verification:
      label: 'Yandex Webmasters Verification'
      type: sequence
      sequence:
        type: string
        label: 'Code'

vbase.settings.tags:
  type: config_object
  label: 'VBase content protection settings'
  mapping:
    node_bundles:
      label: 'Node Bundles'
      type: sequence
      sequence:
        type: string
        label: 'Node Bundle'

vbase.settings.developers:
  type: config_object
  label: 'VBase developers settings'
  mapping:
    developed:
      type: boolean
      label: 'Developed'
    maintained:
      type: boolean
      label: 'Maintained'
    label:
      type: boolean
      label: 'Label'
    width:
      type: integer
      label: 'Width'
    logo:
      type: string
      label: 'Logo'

