vbase.settings.tags:
  type: config_object
  label: 'Tags Settings'
  mapping:
    generator:
      type: boolean
      label: 'Show generator metatag'
    mobile:
      type: boolean
      label: 'Show mobile optimized metatags'
    viewport:
      type: boolean
      label: 'Show viewport metatag'
    telephone:
      type: boolean
      label: 'Telephone detection'
    shortlink:
      type: boolean
      label: 'Show shortlink'
    base:
      type: string
      label: 'Canonical Base Url'

vbase.settings.cp:
  type: config_object
  label: 'Content Protection'
  mapping:
    node_bundles:
      label: 'Node Bundles'
      type: sequence
      sequence:
        type: string
        label: 'Node Bundle'
    taxonomy_vocabularies:
      label: 'Taxonomy Vocabularies'
      type: sequence
      sequence:
        type: string
        label: 'Taxonomy Vocabulary'

vbase.settings.developers:
  type: config_object
  label: 'Developers Settings'
  mapping:
    developed:
      type: boolean
      label: 'Developed'
    maintained:
      type: boolean
      label: 'Maintained'
    label:
      type: boolean
      label: 'Label'
    width:
      type: integer
      label: 'Width'
    logo:
      type: string
      label: 'Logo'

vbase.settings.antispam:
  type: config_object
  label: 'Anti Spam'
  mapping:
    site_key:
      type: string
      label: 'Site Key'
    secret_key:
      type: string
      label: 'Secret Key'
    forms:
      label: 'Forms'
      type: sequence
      sequence:
        type: string
        label: 'Form Id'

vbase.settings.browsers:
  type: config_object
  label: 'Browsers Support'
  mapping:
    ie:
      type: string
      label: 'Internet Explorer'
