<?php

/**
 * @file
 * Functions to support theming in the VCurrent theme.
 */

function vcurrent_preprocess_breadcrumb(&$variables) {
  $request = \Drupal::request();
  $route_match = \Drupal::routeMatch();
  $title = strip_tags(_vbase_get_title());
  $variables['breadcrumb'][] = ['text' => $title];
  $variables['#cache']['contexts'][] = 'languages';
  $variables['#cache']['contexts'][] = 'url';
}
